/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package edu.guilford.studentproject;

import java.awt.Color;
import java.util.ArrayList;
import java.util.Random;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.io.FileWriter;
import java.io.BufferedWriter;

/**
 *
 * @author ewong
 */
public class CreateStudentEvaluation extends javax.swing.JPanel {

    ArrayList<Student> students;

    /**
     * Creates new form CreateStudentEvaluation
     */
    public CreateStudentEvaluation(ArrayList<Student> students) {
        initComponents();
        this.students = students;

        studentnameLabel.setText("Student First & Last Name");
        guilfordCreditsLabel.setText("Guilford Credits");
        transferCreditsLabel.setText("Transfer Credits");
        examCreditsLabel.setText("Exam Credits");
        //studyAwayLabel.setText("Study Away? true/false:");
        studentAthleteLabel.setText("Athlete?");
        inSeasonLabel.setText("In Season?");
        athleticTeamLabel.setText("Athletic Team:");
        studentGpaLabel.setText("Student GPA");
        studentDisabilityLabel.setText("Disability?");
        studentGraduationYearLabel.setText("Graduation Year");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        athleticTeamList = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        guilfordCreditsLabel = new javax.swing.JLabel();
        guilfordText = new javax.swing.JTextField();
        studentIDButton = new java.awt.Button();
        studentIDText = new javax.swing.JTextField();
        transferCreditsLabel = new javax.swing.JLabel();
        transferText = new javax.swing.JTextField();
        examCreditsLabel = new javax.swing.JLabel();
        examText = new javax.swing.JTextField();
        studyAwayLabel = new javax.swing.JLabel();
        studyAwayLabel1 = new javax.swing.JLabel();
        StudyAwayCheckBox = new javax.swing.JCheckBox();
        studentAthleteLabel = new javax.swing.JLabel();
        studentAthleteLabel1 = new javax.swing.JLabel();
        StudenAthleteCheckBox = new javax.swing.JCheckBox();
        inSeasonLabel = new javax.swing.JLabel();
        inSeasonLabel1 = new javax.swing.JLabel();
        InSeasonCheckBox = new javax.swing.JCheckBox();
        studentGpaLabel = new javax.swing.JLabel();
        studentGpaText = new javax.swing.JTextField();
        athleticTeamLabel = new javax.swing.JLabel();
        studentGraduationYearLabel = new javax.swing.JLabel();
        studentGraduationYearText = new javax.swing.JTextField();
        studentDisabilityLabel = new javax.swing.JLabel();
        studentDisabilityLabel1 = new javax.swing.JLabel();
        StudentDisabilityCheckBox = new javax.swing.JCheckBox();
        earlyCollegeLabel1 = new javax.swing.JLabel();
        EarlyCollegeCheckBox = new javax.swing.JCheckBox();
        submitButton = new javax.swing.JButton();
        SubmitArea1 = new java.awt.TextArea();
        resetButton = new javax.swing.JButton();
        studentnameLabel = new javax.swing.JLabel();
        studentNameText = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        CloseButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel2 = new javax.swing.JLabel();
        earlyCollegeLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 204));
        setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 51, 102)));
        setAutoscrolls(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setName(""); // NOI18N
        setNextFocusableComponent(CloseButton);

        athleticTeamList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "NONE", "Men basketball", "Women basketball", "Men cross country", "Women cross country", "Men lacrosse", "Women lacrosse", "Men rugby", "Women rugby", "Men soccer", "Women soccer", "Men softball", "Women softball", "Men swimming", "Women swimming", "Men tennis", "Women tennis", "Men track and field", "Women track and field", "Men triathlon", "Women triathlon", "Men volleyball", "Women volleyball", " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        athleticTeamList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                athleticTeamListMouseClicked(evt);
            }
        });
        athleticTeamList.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                athleticTeamListKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(athleticTeamList);

        jLabel1.setBackground(new java.awt.Color(153, 204, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("STUDENT REGISTRATION EVALUATION");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel1.setOpaque(true);

        guilfordCreditsLabel.setBackground(new java.awt.Color(204, 255, 255));
        guilfordCreditsLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        guilfordCreditsLabel.setText("Student Guilford Credits");
        guilfordCreditsLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        guilfordCreditsLabel.setOpaque(true);

        guilfordText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                guilfordTextMouseClicked(evt);
            }
        });
        guilfordText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guilfordTextActionPerformed(evt);
            }
        });

        studentIDButton.setBackground(new java.awt.Color(102, 255, 204));
        studentIDButton.setLabel("Click to Obtain StudentID");
        studentIDButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentIDButtonActionPerformed(evt);
            }
        });

        studentIDText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                studentIDTextMouseClicked(evt);
            }
        });
        studentIDText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentIDTextActionPerformed(evt);
            }
        });

        transferCreditsLabel.setBackground(new java.awt.Color(204, 255, 255));
        transferCreditsLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        transferCreditsLabel.setText("Student Transfer Credit");
        transferCreditsLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        transferCreditsLabel.setOpaque(true);

        transferText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transferTextActionPerformed(evt);
            }
        });

        examCreditsLabel.setBackground(new java.awt.Color(204, 255, 255));
        examCreditsLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        examCreditsLabel.setText("Student Exam Credits");
        examCreditsLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        examCreditsLabel.setOpaque(true);

        examText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                examTextActionPerformed(evt);
            }
        });

        studyAwayLabel.setBackground(new java.awt.Color(204, 255, 255));
        studyAwayLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        studyAwayLabel.setText("Study Away?");
        studyAwayLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        studyAwayLabel.setOpaque(true);

        studyAwayLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        StudyAwayCheckBox.setText("True");
        StudyAwayCheckBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StudyAwayCheckBoxMouseClicked(evt);
            }
        });
        StudyAwayCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudyAwayCheckBoxActionPerformed(evt);
            }
        });

        studentAthleteLabel.setBackground(new java.awt.Color(204, 255, 255));
        studentAthleteLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        studentAthleteLabel.setText("Student Athlete?");
        studentAthleteLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        studentAthleteLabel.setOpaque(true);

        studentAthleteLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        StudenAthleteCheckBox.setText("True");
        StudenAthleteCheckBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StudenAthleteCheckBoxMouseClicked(evt);
            }
        });
        StudenAthleteCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudenAthleteCheckBoxActionPerformed(evt);
            }
        });

        inSeasonLabel.setBackground(new java.awt.Color(204, 255, 255));
        inSeasonLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        inSeasonLabel.setText("In Season? ");
        inSeasonLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        inSeasonLabel.setOpaque(true);

        inSeasonLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        InSeasonCheckBox.setText("True");
        InSeasonCheckBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InSeasonCheckBoxMouseClicked(evt);
            }
        });
        InSeasonCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InSeasonCheckBoxActionPerformed(evt);
            }
        });

        studentGpaLabel.setBackground(new java.awt.Color(204, 255, 255));
        studentGpaLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        studentGpaLabel.setText("Student GPA");
        studentGpaLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        studentGpaLabel.setOpaque(true);

        studentGpaText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                studentGpaTextMouseClicked(evt);
            }
        });
        studentGpaText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentGpaTextActionPerformed(evt);
            }
        });

        athleticTeamLabel.setBackground(new java.awt.Color(204, 255, 255));
        athleticTeamLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        athleticTeamLabel.setText("Select Athletic Team? ");
        athleticTeamLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        athleticTeamLabel.setOpaque(true);

        studentGraduationYearLabel.setBackground(new java.awt.Color(204, 255, 255));
        studentGraduationYearLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        studentGraduationYearLabel.setText("Student Graduation Year:");
        studentGraduationYearLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        studentGraduationYearLabel.setOpaque(true);

        studentGraduationYearText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                studentGraduationYearTextMouseClicked(evt);
            }
        });
        studentGraduationYearText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentGraduationYearTextActionPerformed(evt);
            }
        });

        studentDisabilityLabel.setBackground(new java.awt.Color(204, 255, 255));
        studentDisabilityLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        studentDisabilityLabel.setText("Student Disability? ");
        studentDisabilityLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        studentDisabilityLabel.setOpaque(true);

        studentDisabilityLabel1.setBackground(new java.awt.Color(153, 204, 255));
        studentDisabilityLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        StudentDisabilityCheckBox.setText("True");
        StudentDisabilityCheckBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StudentDisabilityCheckBoxMouseClicked(evt);
            }
        });
        StudentDisabilityCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentDisabilityCheckBoxActionPerformed(evt);
            }
        });

        earlyCollegeLabel1.setBackground(new java.awt.Color(153, 204, 255));
        earlyCollegeLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        EarlyCollegeCheckBox.setText("True");
        EarlyCollegeCheckBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EarlyCollegeCheckBoxMouseClicked(evt);
            }
        });
        EarlyCollegeCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EarlyCollegeCheckBoxActionPerformed(evt);
            }
        });

        submitButton.setBackground(new java.awt.Color(255, 255, 0));
        submitButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        submitButton.setForeground(new java.awt.Color(255, 51, 51));
        submitButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        submitButton.setLabel("SUBMIT");
        submitButton.setOpaque(true);
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        SubmitArea1.setBackground(new java.awt.Color(204, 204, 204));
        SubmitArea1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SubmitArea1MouseClicked(evt);
            }
        });
        SubmitArea1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                SubmitArea1KeyPressed(evt);
            }
        });

        resetButton.setBackground(new java.awt.Color(255, 102, 51));
        resetButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        resetButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        resetButton.setLabel("CLEAR");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        studentnameLabel.setBackground(new java.awt.Color(204, 255, 255));
        studentnameLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        studentnameLabel.setText("Student First & Last Name");
        studentnameLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        studentnameLabel.setOpaque(true);

        studentNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentNameTextActionPerformed(evt);
            }
        });

       jLabel3.setIcon(new javax.swing.ImageIcon("/studentproject/Blue-hot-air2.png"));

        CloseButton.setBackground(new java.awt.Color(51, 102, 255));
        CloseButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CloseButton.setForeground(new java.awt.Color(255, 255, 0));
        CloseButton.setText("Close");
        CloseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel3.setIcon(new javax.swing.ImageIcon("/studentproject/balloons-Resized2.png"));
        earlyCollegeLabel2.setBackground(new java.awt.Color(204, 255, 255));
        earlyCollegeLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        earlyCollegeLabel2.setText("Early College?");
        earlyCollegeLabel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        earlyCollegeLabel2.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(studentnameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(studentIDButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(studentIDText, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(guilfordCreditsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(guilfordText, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(transferCreditsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(transferText, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(examCreditsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(examText, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(studyAwayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)
                                .addComponent(studyAwayLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(StudyAwayCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(90, 90, 90)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(studentAthleteLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(7, 7, 7)
                                        .addComponent(studentAthleteLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(StudenAthleteCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(inSeasonLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)
                                        .addComponent(inSeasonLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(earlyCollegeLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)
                                        .addComponent(earlyCollegeLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(EarlyCollegeCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(InSeasonCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(studentGpaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(athleticTeamLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(studentDisabilityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6)
                                        .addComponent(studentDisabilityLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(StudentDisabilityCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(studentGraduationYearLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(210, 210, 210)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)
                                        .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(SubmitArea1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(170, 170, 170)
                                        .addComponent(resetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(23, 23, 23)
                                        .addComponent(CloseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(30, 30, 30)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1083, 1083, 1083))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(287, 287, 287)
                                .addComponent(studentGraduationYearText, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(studentNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(287, 287, 287)
                                .addComponent(studentGpaText, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 920, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1080, 1080, 1080))))
            .addGroup(layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 921, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(studentnameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(studentIDButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(studentIDText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(guilfordCreditsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(guilfordText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(transferCreditsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(transferText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(examCreditsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(examText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(studyAwayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(studyAwayLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addComponent(StudyAwayCheckBox))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(studentAthleteLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(studentAthleteLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20)
                                .addComponent(StudenAthleteCheckBox)
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(inSeasonLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(inSeasonLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(earlyCollegeLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(earlyCollegeLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20)
                                .addComponent(EarlyCollegeCheckBox))
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(InSeasonCheckBox)
                                .addGap(18, 18, 18)
                                .addComponent(studentGpaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(62, 62, 62)
                                .addComponent(athleticTeamLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(studentDisabilityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(studentDisabilityLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(21, 21, 21)
                                .addComponent(StudentDisabilityCheckBox)
                                .addGap(20, 20, 20)
                                .addComponent(studentGraduationYearLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(10, 10, 10)
                                .addComponent(SubmitArea1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(resetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CloseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(610, 610, 610)
                        .addComponent(studentGraduationYearText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(studentNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(330, 330, 330)
                        .addComponent(studentGpaText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void guilfordTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guilfordTextActionPerformed
        // TODO add your handling code here:
        String guilfordString = guilfordText.getText();
        double guilfordCredits = Double.parseDouble(guilfordString);
        Color totalColor = new Color(153, 204, 255);
        guilfordCreditsLabel.setBackground(totalColor);
        guilfordCreditsLabel.setOpaque(true);
        Color textColor = new Color(0, 0, 0);
        guilfordCreditsLabel.setForeground(textColor);
        guilfordCreditsLabel.setText("Guilford Credits: " + guilfordCredits);

    }//GEN-LAST:event_guilfordTextActionPerformed

    private void transferTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transferTextActionPerformed
        // TODO add your handling code here:
        String transferString = transferText.getText();
        double transferCredits = Double.parseDouble(transferString);
        Color totalColor = new Color(153, 204, 255);
        transferCreditsLabel.setBackground(totalColor);
        transferCreditsLabel.setOpaque(true);
        Color textColor = new Color(0, 0, 0);
        transferCreditsLabel.setForeground(textColor);
        transferCreditsLabel.setText("Transfer Credits: " + transferCredits);

    }//GEN-LAST:event_transferTextActionPerformed

    private void examTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_examTextActionPerformed
        // TODO add your handling code here:
        String examString = examText.getText();
        double examCredits = Double.parseDouble(examString);
        Color totalColor = new Color(153, 204, 255);
        examCreditsLabel.setBackground(totalColor);
        examCreditsLabel.setOpaque(true);
        Color textColor = new Color(0, 0, 0);
        examCreditsLabel.setForeground(textColor);
        examCreditsLabel.setText("Exam Credits: " + examCredits);

    }//GEN-LAST:event_examTextActionPerformed

    private void studentGraduationYearTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentGraduationYearTextActionPerformed
        // TODO add your handling code here:
        String studentGraduationYearString = studentGraduationYearText.getText();
        int studentGraduationYear = Integer.parseInt(studentGraduationYearString);
        Color totalColor = new Color(153, 204, 255);
        studentGraduationYearLabel.setBackground(totalColor);
        studentGraduationYearLabel.setOpaque(true);
        Color textColor = new Color(0, 0, 0);
        studentGraduationYearLabel.setForeground(textColor);
        studentGraduationYearLabel.setText("Graduation Year: " + studentGraduationYear);

    }//GEN-LAST:event_studentGraduationYearTextActionPerformed

    private void studentGpaTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentGpaTextActionPerformed
        // TODO add your handling code here:
        String studentGpaString = studentGpaText.getText();
        double studentGpa = Double.parseDouble(studentGpaString);
        Color totalColor = new Color(153, 204, 255);
        studentGpaLabel.setBackground(totalColor);
        studentGpaLabel.setOpaque(true);
        Color textColor = new Color(0, 0, 0);
        studentGpaLabel.setForeground(textColor);
        studentGpaLabel.setText("GPA: " + studentGpa);

    }//GEN-LAST:event_studentGpaTextActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        // TODO add your handling code here:
        Student nextStudent = new Student(studentNameText.getText());
        nextStudent.setStudentID(Integer.parseInt(studentIDText.getText()));
        nextStudent.setGuilfordCredits(Double.parseDouble(guilfordText.getText()));
        nextStudent.setTransferCredits(Double.parseDouble(transferText.getText()));
        nextStudent.setExamCredits(Double.parseDouble(examText.getText()));
        nextStudent.setStudyAway(Boolean.parseBoolean(studyAwayLabel1.getText()));
        nextStudent.setStudentAthlete(Boolean.parseBoolean(studentAthleteLabel1.getText()));
        nextStudent.setInSeason(Boolean.parseBoolean(inSeasonLabel1.getText()));
        nextStudent.setAthleticTeam(athleticTeamList.getSelectedValue());
        nextStudent.setStudentGpa(Double.parseDouble(studentGpaText.getText()));
        nextStudent.setStudentDisability(Boolean.parseBoolean(studentDisabilityLabel1.getText()));
        nextStudent.setGraduationYear(Integer.parseInt(studentGraduationYearText.getText()));
        nextStudent.setEarlyCollege(Boolean.parseBoolean(earlyCollegeLabel1.getText()));
        SubmitArea1.setText(nextStudent.toSubmitString() + "Total Evaluation Credits:  " + String.format("%.2f", nextStudent.calculatePoints()));

        //Append Student Entry into NewStudent.txt file.
        String data = " Append to NewStudent File";
        File newStudentFile = new File("NewStudents.txt");
        if (!newStudentFile.exists()) {
            try {
                newStudentFile.createNewFile();
            } catch (IOException ex) {
                Logger.getLogger(CreateStudentEvaluation.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        FileWriter fileWritter = null;
        try {
            fileWritter = new FileWriter(newStudentFile.getName(), true);
        } catch (IOException ex) {
            Logger.getLogger(CreateStudentEvaluation.class.getName()).log(Level.SEVERE, null, ex);
        }
        try (BufferedWriter bw = new BufferedWriter(fileWritter)) {
            bw.write(nextStudent.toSubmitString() + "Total Evaluation Credits:  " + String.format("%.2f", nextStudent.calculatePoints()));
        } catch (IOException ex) {
            Logger.getLogger(CreateStudentEvaluation.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_submitButtonActionPerformed

    private void guilfordTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guilfordTextMouseClicked
        // TODO add your handling code here:
        String guilfordString = guilfordText.getText();
        double guilfordCredits = Double.parseDouble(guilfordString);
        Color totalColor = new Color(153, 204, 255);
        guilfordCreditsLabel.setBackground(totalColor);
        guilfordCreditsLabel.setOpaque(true);
        Color textColor = new Color(0, 0, 0);
        guilfordCreditsLabel.setForeground(textColor);
        guilfordCreditsLabel.setText("Guilford Credits: " + guilfordCredits);

    }//GEN-LAST:event_guilfordTextMouseClicked

    private void studentGpaTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentGpaTextMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_studentGpaTextMouseClicked

    private void studentGraduationYearTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentGraduationYearTextMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_studentGraduationYearTextMouseClicked

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        // TODO add your handling code here:
        studentnameLabel.setText("Student First & Last Name");
        studentNameText.setText("");
        studentIDText.setText("");
        guilfordCreditsLabel.setText("Enter Student's Guilford Credits");
        guilfordText.setText("");
        transferCreditsLabel.setText("Enter Student's Transfer Credits:");
        transferText.setText("");
        examCreditsLabel.setText("Enter Student's Exam Credits:");
        examText.setText("");
        studyAwayLabel.setText("Study Away?");
        StudyAwayCheckBox.setSelected(false);
        studyAwayLabel1.setText("");
        studentAthleteLabel.setText("Student Athlete? ");
        StudenAthleteCheckBox.setSelected(false);
        studentAthleteLabel1.setText("");
        inSeasonLabel.setText("In Season? ");
        InSeasonCheckBox.setSelected(false);
        inSeasonLabel1.setText("");
        athleticTeamLabel.setText("Athletic Team Select: ");
        athleticTeamList.setSelectedIndex(0);
        studentGpaLabel.setText("Student GPA:");
        studentGpaText.setText("");
        studentDisabilityLabel.setText("Student Disability? ");
        StudentDisabilityCheckBox.setSelected(false);
        studentDisabilityLabel1.setText("");
        studentGraduationYearLabel.setText("Graduation Year:");
        studentGraduationYearText.setText("");
        EarlyCollegeCheckBox.setSelected(false);
        earlyCollegeLabel1.setText("");
        SubmitArea1.setText("");


    }//GEN-LAST:event_resetButtonActionPerformed

    private void athleticTeamListKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_athleticTeamListKeyPressed
        // TODO add your handling code here:
        String athleticTeamString = athleticTeamList.getSelectedValue();
        Color totalColor = new Color(153, 204, 255);
        athleticTeamLabel.setBackground(totalColor);
        athleticTeamLabel.setOpaque(true);
        Color textColor = new Color(0, 0, 0);
        athleticTeamLabel.setForeground(textColor);
        athleticTeamLabel.setText("Athletic Team: " + athleticTeamString);

    }//GEN-LAST:event_athleticTeamListKeyPressed

    private void athleticTeamListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_athleticTeamListMouseClicked

        // TODO add your handling code here:
        String athleticTeamString = athleticTeamList.getSelectedValue();
        Color totalColor = new Color(153, 204, 255);
        athleticTeamLabel.setBackground(totalColor);
        athleticTeamLabel.setOpaque(true);
        Color textColor = new Color(0, 0, 0);
        athleticTeamLabel.setForeground(textColor);
        athleticTeamLabel.setText("Athletic Team: " + athleticTeamString);

    }//GEN-LAST:event_athleticTeamListMouseClicked

    private void SubmitArea1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubmitArea1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_SubmitArea1MouseClicked

    private void SubmitArea1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SubmitArea1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_SubmitArea1KeyPressed

    private void studentIDTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentIDTextMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_studentIDTextMouseClicked

    private void studentIDTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentIDTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studentIDTextActionPerformed

    private void studentIDButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentIDButtonActionPerformed
        // TODO add your handling code here:
        Random randGenerator = new Random();
        int studentNumber;
        studentNumber = randGenerator.nextInt(1000000);
        studentIDText.setText(String.format("%08d", studentNumber));


    }//GEN-LAST:event_studentIDButtonActionPerformed

    private void StudyAwayCheckBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StudyAwayCheckBoxMouseClicked
        // TODO add your handling code here:
        if (this.StudyAwayCheckBox.isSelected()) {
            studyAwayLabel1.setText("true");
        }
        Color totalColor = new Color(153, 204, 255);
        studyAwayLabel1.setBackground(totalColor);
        studyAwayLabel1.setOpaque(true);
        Color textColor = new Color(0, 0, 0);
        studyAwayLabel1.setForeground(textColor);
    }//GEN-LAST:event_StudyAwayCheckBoxMouseClicked

    private void StudyAwayCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudyAwayCheckBoxActionPerformed
        // TODO add your handling code here:
        if (this.StudyAwayCheckBox.isSelected()) {
            studyAwayLabel1.setText("true");
        }
        Color totalColor = new Color(153, 204, 255);
        studyAwayLabel1.setBackground(totalColor);
        studyAwayLabel1.setOpaque(true);
        Color textColor = new Color(0, 0, 0);
        studyAwayLabel1.setForeground(textColor);
    }//GEN-LAST:event_StudyAwayCheckBoxActionPerformed

    private void StudentDisabilityCheckBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StudentDisabilityCheckBoxMouseClicked
        // TODO add your handling code here:
        if (this.StudentDisabilityCheckBox.isSelected()) {
            studentDisabilityLabel1.setText("true");

        }
        Color totalColor = new Color(153, 204, 255);
        studentDisabilityLabel1.setBackground(totalColor);
        studentDisabilityLabel1.setOpaque(true);
        Color textColor = new Color(0, 0, 0);
        studentDisabilityLabel1.setForeground(textColor);
    }//GEN-LAST:event_StudentDisabilityCheckBoxMouseClicked

    private void StudentDisabilityCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentDisabilityCheckBoxActionPerformed
        // TODO add your handling code here:
        if (this.StudentDisabilityCheckBox.isSelected()) {
            studentDisabilityLabel1.setText("true");

        }
        Color totalColor = new Color(153, 204, 255);
        studentDisabilityLabel1.setBackground(totalColor);
        studentDisabilityLabel1.setOpaque(true);
        Color textColor = new Color(0, 0, 0);
        studentDisabilityLabel1.setForeground(textColor);
    }//GEN-LAST:event_StudentDisabilityCheckBoxActionPerformed

    private void EarlyCollegeCheckBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EarlyCollegeCheckBoxMouseClicked
        // TODO add your handling code here:
        if (this.EarlyCollegeCheckBox.isSelected()) {
            earlyCollegeLabel1.setText("true");

        }
        Color totalColor = new Color(153, 204, 255);
        earlyCollegeLabel1.setBackground(totalColor);
        earlyCollegeLabel1.setOpaque(true);
        Color textColor = new Color(0, 0, 0);
        earlyCollegeLabel1.setForeground(textColor);
    }//GEN-LAST:event_EarlyCollegeCheckBoxMouseClicked

    private void EarlyCollegeCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EarlyCollegeCheckBoxActionPerformed
        // TODO add your handling code here:
        if (this.EarlyCollegeCheckBox.isSelected()) {
            earlyCollegeLabel1.setText("true");

        }
        Color totalColor = new Color(153, 204, 255);
        earlyCollegeLabel1.setBackground(totalColor);
        earlyCollegeLabel1.setOpaque(true);
        Color textColor = new Color(0, 0, 0);
        earlyCollegeLabel1.setForeground(textColor);
    }//GEN-LAST:event_EarlyCollegeCheckBoxActionPerformed

    private void StudenAthleteCheckBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StudenAthleteCheckBoxMouseClicked
        // TODO add your handling code here:
        if (this.StudenAthleteCheckBox.isSelected()) {
            studentAthleteLabel1.setText("true");
        }
        Color totalColor = new Color(153, 204, 255);
        studentAthleteLabel1.setBackground(totalColor);
        studentAthleteLabel1.setOpaque(true);
        Color textColor = new Color(0, 0, 0);
        studentAthleteLabel1.setForeground(textColor);

    }//GEN-LAST:event_StudenAthleteCheckBoxMouseClicked

    private void StudenAthleteCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudenAthleteCheckBoxActionPerformed
        // TODO add your handling code here:
        if (this.StudenAthleteCheckBox.isSelected()) {
            studentAthleteLabel1.setText("true");
        }
        Color totalColor = new Color(153, 204, 255);
        studentAthleteLabel1.setBackground(totalColor);
        studentAthleteLabel1.setOpaque(true);
        Color textColor = new Color(0, 0, 0);
        studentAthleteLabel1.setForeground(textColor);

    }//GEN-LAST:event_StudenAthleteCheckBoxActionPerformed

    private void InSeasonCheckBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InSeasonCheckBoxMouseClicked
        // TODO add your handling code here:
        if (this.InSeasonCheckBox.isSelected()) {
            inSeasonLabel1.setText("true");
        }
        Color totalColor = new Color(153, 204, 255);
        inSeasonLabel1.setBackground(totalColor);
        inSeasonLabel1.setOpaque(true);
        Color textColor = new Color(0, 0, 0);
        inSeasonLabel1.setForeground(textColor);
    }//GEN-LAST:event_InSeasonCheckBoxMouseClicked

    private void InSeasonCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InSeasonCheckBoxActionPerformed
        // TODO add your handling code here:
        if (this.InSeasonCheckBox.isSelected()) {
            inSeasonLabel1.setText("true");
        }
        Color totalColor = new Color(153, 204, 255);
        inSeasonLabel1.setBackground(totalColor);
        inSeasonLabel1.setOpaque(true);
        Color textColor = new Color(0, 0, 0);
        inSeasonLabel1.setForeground(textColor);
    }//GEN-LAST:event_InSeasonCheckBoxActionPerformed

    private void studentNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentNameTextActionPerformed
        // TODO add your handling code here:
        String theName = studentNameText.getText();
        int spaceLocation = theName.indexOf(' ');
        String firstName = theName.substring(0, spaceLocation);
        String ufirstName = firstName.substring(0, 1).toUpperCase();
        String lfirstName = firstName.substring(1).toLowerCase();
        String sfirstName = (ufirstName + lfirstName);
        String lastName = theName.substring(spaceLocation + 1);
        String ulastName = lastName.substring(0, 1).toUpperCase();
        String llastName = lastName.substring(1).toLowerCase();
        String slastName = (ulastName + llastName);
        Color totalColor = new Color(200, 250, 200);
        studentnameLabel.setBackground(totalColor);
        studentnameLabel.setOpaque(true);
        Color textColor = new Color(0, 0, 0);
        studentnameLabel.setForeground(textColor);
        studentnameLabel.setText("Name: " + sfirstName + " " + slastName);
    }//GEN-LAST:event_studentNameTextActionPerformed

    private void CloseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseButtonActionPerformed
        // TODO add your handling code here:
        System.exit(0);
        Color totalColor = new Color(200, 250, 200);
        CloseButton.setBackground(totalColor);
        CloseButton.setOpaque(true);
        Color textColor = new Color(0, 0, 0);
        CloseButton.setForeground(textColor);


    }//GEN-LAST:event_CloseButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CloseButton;
    private javax.swing.JCheckBox EarlyCollegeCheckBox;
    private javax.swing.JCheckBox InSeasonCheckBox;
    private javax.swing.JCheckBox StudenAthleteCheckBox;
    private javax.swing.JCheckBox StudentDisabilityCheckBox;
    private javax.swing.JCheckBox StudyAwayCheckBox;
    private java.awt.TextArea SubmitArea1;
    private javax.swing.JLabel athleticTeamLabel;
    private javax.swing.JList<String> athleticTeamList;
    private javax.swing.JLabel earlyCollegeLabel1;
    private javax.swing.JLabel earlyCollegeLabel2;
    private javax.swing.JLabel examCreditsLabel;
    private javax.swing.JTextField examText;
    private javax.swing.JLabel guilfordCreditsLabel;
    private javax.swing.JTextField guilfordText;
    private javax.swing.JLabel inSeasonLabel;
    private javax.swing.JLabel inSeasonLabel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton resetButton;
    private javax.swing.JLabel studentAthleteLabel;
    private javax.swing.JLabel studentAthleteLabel1;
    private javax.swing.JLabel studentDisabilityLabel;
    private javax.swing.JLabel studentDisabilityLabel1;
    private javax.swing.JLabel studentGpaLabel;
    private javax.swing.JTextField studentGpaText;
    private javax.swing.JLabel studentGraduationYearLabel;
    private javax.swing.JTextField studentGraduationYearText;
    private java.awt.Button studentIDButton;
    private javax.swing.JTextField studentIDText;
    private javax.swing.JTextField studentNameText;
    private javax.swing.JLabel studentnameLabel;
    private javax.swing.JLabel studyAwayLabel;
    private javax.swing.JLabel studyAwayLabel1;
    private javax.swing.JButton submitButton;
    private javax.swing.JLabel transferCreditsLabel;
    private javax.swing.JTextField transferText;
    // End of variables declaration//GEN-END:variables
}
